version: "3.5"

networks:
  web:
    external: false

services:
  nginx:
    image: nginx:alpine
    networks:
      - web
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - client
      - api
    volumes:
      - "client_volume:/var/www/client"
      - "./config/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./ssl:/etc/self-certs"

  api:
    build: "./api"
    networks:
      - web
    depends_on:
      - postgres
    ports:
      - "5000:80"
      - "5001:443"

  client:
    build: "./client"
    volumes:
      - "client_volume:/var/www/client"

  postgres:
    image: postgres:alpine
    shm_size: '1gb'
    environment:
      POSTGRES_DB: finance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5433:5432"
    networks:
      - web
    volumes:
      - "db_volume:/var/lib/postgresql/data"
      - "./config/finance.sql:/docker-entrypoint-initdb.d/seed.sql"

volumes:
  db_volume:
  client_volume:

